### ISSUE TITLE
你好，为什么不能加载那？

### ISSUE THREAD

**Issue by tkdo** [hacktmz/faiss-center#1]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /dev_java_project/githubXm/faiss-center/faiss-client/libfaissjni.so: dlopen(/dev_java_project/githubXm/faiss-center/faiss-client/libfaissjni.so, 1): no suitable image found.  Did find:
	/dev_java_project/githubXm/faiss-center/faiss-client/libfaissjni.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/dev_java_project/githubXm/faiss-center/faiss-client/libfaissjni.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.jiuyan.faiss.LibUtil.loadlibFromFile(LibUtil.java:34)
	at com.jiuyan.faiss.LibUtil.loadFaissLib(LibUtil.java:16)
	at com.jiuyan.faiss.NativeClient.<clinit>(NativeClient.java:39)
	at com.jiuyan.faiss.client.IndexFlatL2.<init>(IndexFlatL2.java:9)
	at com.jiuyan.faiss.test.IndexTest.testIndexL2(IndexTest.java:32)
	at com.jiuyan.faiss.test.IndexTest.main(IndexTest.java:13)

**Comment by cbamls** [comment]
1. 平台不对？
2. LibUtil 里面load方法仔细看看 可能修改该下逻辑
